# Generated by Django 4.2 on 2023-04-09 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('goods', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_category', models.CharField(max_length=32)),
                ('goods_color', models.CharField(max_length=32)),
                ('goods_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 15, 27, 27, 512034, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stuff',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.stuff')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history', models.AutoField(primary_key=True, serialize=False)),
                ('in_out', models.CharField(choices=[('I', '입고'), ('O', '출고'), ('N', '신규')], max_length=1)),
                ('count', models.IntegerField(default=0)),
                ('history_time', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 15, 27, 27, 515034, tzinfo=datetime.timezone.utc))),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.stuff')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
