# Generated by Django 4.2 on 2023-04-09 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 15, 29, 7, 587395, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.stuff'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 15, 29, 7, 584394, tzinfo=datetime.timezone.utc)),
        ),
    ]
