# Generated by Django 4.2 on 2023-04-05 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='id2',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='inbound',
            name='inbound_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 11, 48, 27, 786586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='outbound',
            name='outbound_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 11, 48, 27, 786586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='stuff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 11, 48, 27, 786086, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='stuff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
